from __future__ import annotations

import os
import re
from dataclasses import dataclass

from analyzer import Analysis
from github_client import GitHubClient
from log_collector import redact

MAX_COMMENT_CHARS = 65_000

LOC_RE = re.compile(r"([\w./-]+\.\w+):(\d+):")

@dataclass
class RunContext:
    repo: str
    run_id: str
    workflow: str
    branch: str
    sha: str
    run_url: str

def _fence(lines: list[str]) -> str:
    body = "\n".join(lines).replace("```", "'''")
    return f"```text\n{body}\n```"

def _find_lines(index: dict[str, list[str]], name: str) -> list[str] | None:
    """Match a log path (relative or absolute) to a collected source file."""
    for path, lines in index.items():
        if name == path or name.endswith("/" + path) or path.endswith("/" + name):
            return lines
    return None

def _evidence_block(evidence: list[str], source_files) -> str:
    """each ci error line, followed by the real source line it points to."""
    index = {f.path: f.content.splitlines() for f in source_files or []}
    out: list[str] = []

    for line in evidence:
        out.append(line)

        m = LOC_RE.search(line)
        lines = _find_lines(index, m.group(1)) if m else None

        if lines:
            num = int(m.group(2))
            if 1 <= num <= len(lines):
                out.append(f"    > {lines[num - 1].strip()}")

    return _fence(out)

def build_markdown(
    ctx: RunContext,
    analyses: list[Analysis],
    total_failed: int,
    source_files=None,
) -> str:

    parts = [
        f"<!-- ai-devops-agent run:{ctx.run_id} -->",
        "## AI DevOps Agent: Failure Analysis",
        "",
        f"**Repository:** `{ctx.repo}`  ",
        f"**Workflow:** {ctx.workflow}  ",
        f"**Branch:** `{ctx.branch}`  ",
        f"**Commit:** `{ctx.sha[:7]}`  ",
        f"**Run:** [{ctx.run_id}]({ctx.run_url})",
    ]

    for a in analyses:

        parts += [
            "",
            "---",
            "",
            f"### Job: {a.failed_job}",
            f"**Failed step:** {a.failed_step}  ",
            f"**Category:** {a.category}  ",
            f"**Confidence:** {a.confidence}",
            "",
            "**Root cause:**",
            a.root_cause,
            "",
            "**Suggested fix:**",
            a.suggested_fix,
            "",
            "**Evidence:**",
            _evidence_block(a.evidence, source_files),
        ]

        if a.source_analysis:
            parts += [
                "",
                "**Source Analysis:**",
                a.source_analysis,
            ]

        if a.likely_followup_errors:
            parts += [
                "",
                "**Likely follow-up errors (not yet reported by the compiler):**",
                *[f"- `{e}`" for e in a.likely_followup_errors],
            ]

    if total_failed > len(analyses):
        parts += [
            "",
            f"_{total_failed - len(analyses)} more failed job(s) "
            "not analyzed (limit reached)._",
        ]

    parts += [
        "",
        "<sub>Generated by AI DevOps Agent. Verify before applying.</sub>",
    ]

    return redact("\n".join(parts))[:MAX_COMMENT_CHARS]

def post_pr_comment(
    client: GitHubClient,
    ctx: RunContext,
    pr_number: int,
    markdown: str,
) -> None:

    client.post_pr_comment(ctx.repo, pr_number, markdown)

def write_job_summary(markdown: str) -> None:

    path = os.getenv("GITHUB_STEP_SUMMARY")

    if path:
        with open(path, "a", encoding="utf-8") as fh:
            fh.write(markdown + "\n")
    else:
        print(markdown)